### ISSUE TITLE
Где должны храниться сервисы?

### ISSUE THREAD

**Issue by MikaelMelkonyan** [Maks-Jago/SwiftUI-UDF#11]
Привет. Подскажи пожалуйста, если взять к примеру `KeychainService` то он должен храниться в Store?

При входе в приложение нужно понимать авторизован пользователь или нет. Данная информация зависит от токена / ключа / пары ключей / пары токенов, которые хранятся в Keychains. В AppState можно хранить дефолтное значение isLoggedIn как false, но по идее можно сразу определять есть ли у нас ключи. И вот где по правилам должен находиться сервис, чтобы из него вытащить инфу в AppState?

**Comment by Maks-Jago** [comment]
Привет.
Я в таком случае использую @propertyWrapper.
<img width="753" alt="Screenshot 2021-02-23 at 13 52 14" src="https://user-images.githubusercontent.com/1841811/108840015-71f4f300-75de-11eb-83f3-92f7a1f3dd98.png">

Или

<img width="792" alt="Screenshot 2021-02-23 at 13 52 44" src="https://user-images.githubusercontent.com/1841811/108840023-73beb680-75de-11eb-939f-2ec2b4c36f66.png">

А сами поля конечно хранятся в стейте приложение, в нашем случае это `UserForm` или `UserData`. Задача этой сущности обрабатывать все возможные события которые влияют на пользователя

**Comment by Maks-Jago** [comment]
Все синхронные операции выполняем в Редьюсерах. Классы сервисы выносим Environment объекте или сущности которые инжектятся в редьюсер в явном/неявном виде.

Все асинхронные операции выполняются в Middleware слое

**Comment by Maks-Jago** [comment]
Самая актуальная версию UDF по тегу 1.0.0-alpha.14
Обкатываем новую реализацию и скоро будет стабильная версия

**Comment by MikaelMelkonyan** [comment]
Спасибо за ответ. Пытаюсь разобраться )

**Comment by Maks-Jago** [comment]
Не за что, пиши если что - по возможности отвечать буду. 🖖
