### ISSUE TITLE
Store & EnvironmentStore

### ISSUE THREAD

**Issue by MikaelMelkonyan** [Maks-Jago/SwiftUI-UDF#12]
Подскажи пожалуйста по возможности, что такое EnvironmentStore? Почему Store - не является ObservableObject?

**Comment by Maks-Jago** [comment]
Store разделен на 2 сущности:
1) чистый Store где все редьюсеры и вся логика диспатча событий и мидлвар обсервинг стейта
2) EnvironmentStore - ObservableObject, который хранит в себе актуальный слепок стейта, хранит в себе Store объект и является proxy сущностью и связью со SwiftUI. И который сам является сущностью, которая обсервит изменения стейта и обновляет @Published свойство для перерисовки всего UI

**Comment by MikaelMelkonyan** [comment]
А чего Store сам не является связью со SwiftUI? 
Чтобы решение подходило и без SwiftUI? 
Судя по названию SwiftUI-UDF Package как раз направлен только на SwiftUI + UDF. Поэтому меня немного это заинтересовало. 

Ссори, если вопрос слишком простой

**Comment by Maks-Jago** [comment]
Разделение ответсвенностей

**Comment by MikaelMelkonyan** [comment]
Понял, спасибо ✌️
